### PR TITLE
Release tracking PR: `v0.102.0+22.1`

### PR DESCRIPTION
**Pull request by tcharding**
Add a changelog entry, bump the version, and update the lock files.

### CODE REVIEW

**Comment by tcharding** [comment]
We are right to merge, tag, and release this one please @apoelstra.

**Comment by apoelstra** [comment]
Oops! Don't know how I let over a week go by.

**Review by apoelstra — APPROVED** [review]
ACK ab09cd534fda90e24ade582ee521cfca3e492625

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
