### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by marathon-gary**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
utACK ff85a1a08fb8f1bd29f92f4c5e825532fe87b1be

**Review by tcharding — APPROVED** [review]
ACK ff85a1a08fb8f1bd29f92f4c5e825532fe87b1be

**Comment by tcharding** [comment]
Its so long since we merged here I forget who does it in this repo, its me I think, right @apoelstra?

**Comment by apoelstra** [comment]
I'd prefer if you did it @tcharding, yeah. I think both of us could. For my part, my local CI setup is out of date on this repo and I'd rather avoid updating it for a little while longer ;).

**Comment by tcharding** [comment]
No sweat, merging like its my job!

**Pull request merged**
