### PR TITLE
Vendor Bitcoin Core v24.2

### PR DESCRIPTION
**Pull request by tcharding**
Run the vendoring script:
    
   `./contrib/vendor-bitcoin-core.sh v24.2`

Also, patch the `build.rs` file to add:
    
    `.include("depend/bitcoin/src/secp256k1/include")`

### CODE REVIEW

**Comment by tcharding** [comment]
Not sure what to make of the build failures, `cargo build` works for me locally.

**Comment by tcharding** [comment]
Oh yeah, fixed it!

**Review by apoelstra — APPROVED** [review]
ACK 6730e4696819b0273d6283dc2317a206acb43f35

**Comment by tcharding** [comment]
I've got the release branch on my machine at home, I'll be back there in an hour to rebase it.

**Comment by tcharding** [comment]
Let me know please if you didn't want that merged for some reason.

**Comment by tcharding** [comment]
#90 is ready to go.

**Pull request merged**
