### PR TITLE
Release tracking PR: `v0.101.0+0.21.2` 

### PR DESCRIPTION
**Pull request by tcharding**
Add changelog and bump the version.

### CODE REVIEW

**Comment by tcharding** [comment]
There was a typo in yesterdays tag, I've fixed it up, delete  the wrong one and pushed the new one, you will see the wrong one locally still @apoelstra

**Comment by tcharding** [comment]
phew! I woke up in the night and remembered I hadn't built `rust-bitcoin` with this version. Now done, and for the `v0.101.1+0.21-final` PR too.

**Comment by apoelstra** [comment]
The tag you pushed appeared to be unsigned so I replaced it with a signed one :). It should be correct now.

**Comment by apoelstra** [comment]
As before, can you separate the "bump version and release" commit into its own PR?

**Comment by tcharding** [comment]
Oh yep, can do. Can you tell me what your scripts don't like about it when its together in a single PR, perhaps then I will internalise it and remember for future.

**Comment by apoelstra** [comment]
@tcharding it causes my lockfiles to change partway through the PR. But the lockfiles are provided externally and I can't specify different ones for different commits (my scripts automatically compute the set of commits per PR, I don't know them and can't attach metadata to them).

An alternate solution would be to pull the lockfiles into the crate, like we do with rust-bitcoin and rust-secp.

**Comment by tcharding** [comment]
> An alternate solution would be to pull the lockfiles into the crate, like we do with rust-bitcoin and rust-secp.

So for those you just run CI with recent and minimal lockfiles? I can do that same set up here if it helps.

**Comment by apoelstra** [comment]
>So for those you just run CI with recent and minimal lockfiles? I can do that same set up here if it helps.

Yeah. That'd be great.

**Comment by tcharding** [comment]
Next step is #81 and then this one - BOOM.

**Comment by tcharding** [comment]
Please ack, merge, tag, publish, and party.

**Review by apoelstra — APPROVED** [review]
ACK 119126f12cfe7b734d81b57047a5ca4c12500749

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
