### PR TITLE
Increase secp256k1 version

### PR DESCRIPTION
**Pull request by rodoufu**
- Increase `secp256k1` version;
- Remove ununsed code;

It supposes to fix a problem using `bitcoin` crate.
```sh
required by package `bitcoin v0.22.0`
    ... which is depended on by `your_project`
versions that meet the requirements `^0.15` are: 0.15.5, 0.15.3, 0.15.2, 0.15.1, 0.15.0
```

### CODE REVIEW

**Comment by tamasblummer** [comment]
bitcoin 0.22 is not yet released see other pull request here. the fix for u64 is neat, separate that for now please

**Comment by rodoufu** [comment]
> bitcoin 0.22 is not yet released see other pull request here. the fix for u64 is neat, separate that for now please

I've just separated it.
I've removed `use std::env;` from `build.rs` cause it was not used, @tamasblummer do you want me to keep that file unchanged?

**Comment by elichai** [comment]
I think we can close this

**Comment by rodoufu** [comment]
> I think we can close this

I have specified the version of:
```rust
secp256k1 = { version = "0.16", features = ["recovery"] }
```
Cause the build was failing when using with hdwallet and ethereum-tx-sign.

**Comment by stevenroose** [comment]
@rodoufu In the new version of this crate, we're not using rust-secp256k1 anymore at all. Can you test if all works for you and make a new issue in case you have a problem?

**Comment by rodoufu** [comment]
> @rodoufu In the new version of this crate, we're not using rust-secp256k1 anymore at all. Can you test if all works for you and make a new issue in case you have a problem?
@stevenroose I've seen that the new version https://crates.io/crates/bitcoinconsensus/0.19.0-1 does not uses it, you're right, I'm going to try, thanks.

**Pull request closed without merging**
