### PR TITLE
Vendor Bitcoin Core v23.2

### PR DESCRIPTION
**Pull request by tcharding**
Run the vendoring script:
    
   `./contrib/vendor-bitcoin-core.sh v23.2`

### CODE REVIEW

**Comment by tcharding** [comment]
> Or a different big-endian box?

Yeah I had a bit of a scout around and didn't see one - I can look harder though.

**Comment by apoelstra** [comment]
For now I think we should just mark this CI job as optional :/. Let's get caught up with Core and then revisit this rather than having this open loop where we're struggling to deal with old code on old CI boxes and unable to move forward.

**Comment by tcharding** [comment]
Let's go!

**Comment by tcharding** [comment]
Gentle bump, can you take a look at this one please @apoelstra.

**Review by apoelstra — APPROVED** [review]
ACK 1b8dd2e9b949399700ac94f3f35e338536b80c23

**Comment by tcharding** [comment]
Is this queued up for merge today @apoelstra ?

**Pull request merged**
