### PR TITLE
bump version to 0.19.0-3

### PR DESCRIPTION
**Pull request by apoelstra**
Changes since 0.19.0-2 were to add some extra `#derive`s, fix some dep pinning in Cargo.toml, and changing `u64` to `uint64_t` in a couple of places in the FFI.

### CODE REVIEW

**Comment by stevenroose** [comment]
Want, aren't we following the upstream versions here? So if we bump to 0.19.1, shouldn't we be updating the depends as well? Otherwise it'd have to be `0.19.0-3` perhaps?

**Comment by apoelstra** [comment]
Ah! I misunderstood. Let me change it.

**Comment by TheBlueMatt** [comment]
Should we land #23 first?

**Comment by dr-orlovsky** [comment]
Seems we either need to bump MSRV or pin `cc` because of CI failure

**Comment by apoelstra** [comment]
We just need to fix CI.

**Review by dr-orlovsky — APPROVED** [review]

**Review by stevenroose — APPROVED** [review]

**Pull request merged**
