### PR TITLE
Update Bitcoin Core dependency to 0.21.2

### PR DESCRIPTION
**Pull request by tcharding**
EDIT: This breaks the "external-secp" feature. I am unable to work it out at the current time. @elichai I see in commit `3e0009474bc` that you added the feature, should I be trying to link in an external static lib? I tried passing one into the build script using an env var and calling `consensus_config.include(<path from env var>) but to no avail.

Currently we are vendoring the source code from Bitcoin Core `v0.20.1`.

Update the subtree to use branch `0.21.2` using:
```
git subtree pull --prefix='depend/bitcoin'  git@github.com:bitcoin/bitcoin.git v0.21.2 --squash
```

Includes changes to the build script by @jrawsthorne  and update to the C++ toolchain suggested by @ulrichard in #31. 

**Note**: The subtree update produces two commits **that do not build**. The patch to fix the build as done separately.

Close: #31

### CODE REVIEW

**Comment by tcharding** [comment]
Convert to draft until #49 / #51 resolve.

**Comment by tcharding** [comment]
hmmm, the clippy fail here uncovered a bug in CI, we are not testing features. (clippy is running with `--all-features` so build failure in "external-secp" feature is showing up there).

**Comment by jrawsthorne** [comment]
Were the C/C++ build issues ever resolved with this? Following up on this because the next core release will contain support for Taproot verification which is a nice addition (https://github.com/bitcoin/bitcoin/pull/28539) so it would be good to resolve any remaining build issues

**Comment by tcharding** [comment]
Now on top of #67

**Comment by tcharding** [comment]
Superseded by #68

**Pull request closed without merging**
