### PR TITLE
Improve crate

### PR DESCRIPTION
**Pull request by tcharding**
Go through https://github.com/rust-bitcoin/rust-bitcoin/issues/1649 and attempt to verify that we have every t crossed and i dotted.

With this PR I believe we could consider stabilising the `bitcoinconsensus` crate, am I wrong? Are there any considerations re the semver number we are using or the fact that we are wrapping 0.20.0 Bitcoin Core?

### CODE REVIEW

**Comment by tcharding** [comment]
Pushed three patches to the front of the PR to fix fmt and clippy issues. No changes to the other patches.

**Review by apoelstra — APPROVED** [review]
ACK ddd61f0641a232a726ada8743a50696ec7fc0d3e

**Comment by Kixunil** [comment]
I think we could just make the interface around `libbitcoinconsensus` wrapped in `bitcoin` so if the API changes here we can still avoid breakage downstream.

**Comment by tcharding** [comment]
Can you clarify please, do you mean
1. Hide `libbitcoinconsensus` within `rust-bitcoinconsesus` (eg make `bitcoinconsensus_verify_script_with_amount` private)
2. Don't expose `rust-bitcoinconsensus` in the public API of `rust-bitcoin` (eg, remove the `bitcoinconsensus` error type from our public errors)

**Comment by stevenroose** [comment]
For crates like this, to avoid change-the-world changes, we could use range dependency indicators like `bitcoin = ">=0.28.0,<0.31.0"`. I'm thinking about those a lot recently, unfortunately one would have to test all the versions in between in CI somehow. But for a crate like this that only uses some basic types, it makes sense to not make dependency version bumps breaking changes.

**Comment by Kixunil** [comment]
@tcharding I mean 2.

@stevenroose I was thinking the same recently. I might start doing it in some of my projects.

**Comment by stevenroose** [comment]
rust-bitcoin doesn't have to do much as a crate. Other than try be mindful of breaking changes which we already are. The org/ecosystem could develop a way to extend the github CI spec to allow building with various versions of a certain crate pinned.

**Pull request merged**
