### PR TITLE
Release tracknig PR: `v0.103.0+23.2`

### PR DESCRIPTION
**Pull request by tcharding**
Add a changelog entry, bump the version, and update the lock files.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK b73899f3cfc57f477750cd6bdeb5c981be09a4be

**Comment by apoelstra** [comment]
`cargo publish` is failing with

```
  cargo:warning=depend/bitcoin/src/primitives/transaction.h:10:10: fatal error: consensus/amount.h: No such file or directory

  cargo:warning=   10 | #include <consensus/amount.h>

  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~
```

This doesn't happen with `cargo test` or `cargo build` or any other cargo invocation I can think of.

**Comment by apoelstra** [comment]
I think we need to remove `/bitcoin/src/consensus/**` from the Cargo.toml exclude list.

Tamas added this in 876dc722ce8. It looks like a clumsy way of excluding all the source code that exists in Core but isn't used by libbitcoinconsensus. Arguably we should revert that whole commit, but maybe we should just remove the specific directories that we need to remove. Which in this case is `src/consensus`.

**Comment by tcharding** [comment]
Fixed as suggested in #88.

**Pull request merged**
