### PR TITLE
Move to using git subtree with `--squash`

### PR DESCRIPTION
**Pull request by tcharding**
Same as #49 but uses `--squash`. Done to see if its better, obviously we do not want to merge both, one should be closed in favour of the other.

Add a git subtree, I could not get the git subtree add command to use a commit hash so I used a tag - this led me to using v0.19.2 instead of the commit hash we are currently on (six commits after tag v0.19.0).

Includes docs in the README and a version bump so this can be merged and release directly if so desired.

### CODE REVIEW

**Comment by tcharding** [comment]
This and #49 have been open for almost a month now, in a few days I'm going to merge this one (using `--squash`), and close #49. Flagging here in case @apoelstra wants to add anything or veto the merge.

**Comment by apoelstra** [comment]
No veto. Go for it!

**Comment by tcharding** [comment]
Woops, there are no acks on this one @apoelstra :)

**Comment by tcharding** [comment]
Turns out I can merge without acks, I took your 'No veto. Go for it!' as an implicit ack.

**Pull request merged**
