### PR TITLE
Add CI script and minimal/recent lock files

### PR DESCRIPTION
**Pull request by tcharding**
Add test scripts and lock files, as well as updating the github actions, to mimic how we do things in `rust-secp256k1`.

### CODE REVIEW

**Comment by tcharding** [comment]
I'm not entirely sure how all these changes are going to fit in with your local CI @apoelstra, if there as a preferred ordering for these changes I can re-do things. My guess is that this can be rebased and merge after #79 and then we do #77

**Comment by tcharding** [comment]
This is the next step @apoelstra in the epic Core upgrade process.

**Comment by apoelstra** [comment]
Nice! As a nit, I kinda prefer the Cargo-minimal.lock file actually have minimum deps (`cc` I think can be 1.0.28 as it is in some other projcets). But I'm not too concerned about this. Fine to just use the existing values as "minimum supported" ones since we know they work with our MSRV.

**Comment by apoelstra** [comment]
Gonna go ahead and merge -- my local CI script is now broken without this :) so I'd prefer if we merge it ASAP. If we want to tweak the lockfiles we can do it in a future PR.

**Pull request merged**
